import {test,expect} from '@playwright/test'
import path from 'node:path'
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'

test('real UI, API, worker, PostgreSQL and Qdrant with synthetic HTTP model contracts',async({page,request})=>{
  const name='browser-contract-'+Date.now()
  let kbId='',convId=''
  try{
    await page.goto('/')
    await page.getByRole('button',{name:'新建知识库'}).click()
    await page.getByLabel('名称',{exact:true}).fill(name)
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await page.getByRole('heading',{name,exact:true}).click()
    const bases=await (await request.get('/api/knowledge-bases')).json()
    kbId=bases.find((k:{name:string})=>k.name===name).id
    await page.getByRole('button',{name:/数据源 0/}).click()
    await page.getByRole('button',{name:'添加数据源'}).click()
    await page.getByLabel('名称',{exact:true}).fill('上传验收')
    await page.getByRole('button',{name:'保存',exact:true}).click()
    const chooser=page.waitForEvent('filechooser')
    await page.getByRole('button',{name:'选择文件',exact:true}).click()
    await (await chooser).setFiles(path.resolve('../fixtures/retrieval/guide.txt'))
    await expect(page.getByText('guide.txt · 新增')).toBeVisible()
    await page.getByRole('button',{name:/文档 1/}).click()
    await expect(page.getByText('已索引',{exact:true})).toBeVisible({timeout:30000})
    await page.getByRole('button',{name:'查看片段'}).click()
    await expect(page.locator('.drawer')).toContainText('本地 OCR')
    await page.getByRole('button',{name:'关闭来源'}).click()
    await page.getByRole('button',{name:/数据源 1/}).click()
    const replacement=page.waitForEvent('filechooser')
    await page.getByRole('button',{name:'选择文件',exact:true}).click()
    await (await replacement).setFiles(path.resolve('../fixtures/retrieval/guide.txt'))
    await expect(page.getByText('guide.txt · 未变化')).toBeVisible()
    await page.getByRole('button',{name:'开始问答'}).click()
    await page.getByRole('textbox',{name:'问题',exact:true}).fill('支持哪些文件格式？')
    await page.getByRole('button',{name:'发送问题'}).click()
    await expect(page.locator('.message.assistant')).toContainText('扫描件通过本地 OCR')
    await expect(page.getByRole('button',{name:'发送问题'})).toBeVisible()
    await page.locator('.citation').first().click()
    await expect(page.locator('.drawer')).toContainText('本地 OCR')
    await page.getByRole('button',{name:'关闭来源'}).click()
    await page.getByRole('textbox',{name:'问题',exact:true}).fill('它支持扫描件吗？')
    await page.getByRole('button',{name:'发送问题'}).click()
    await expect(page.locator('.message.assistant')).toHaveCount(2)
    await expect(page.getByRole('button',{name:'发送问题'})).toBeVisible()
    const conversations=await (await request.get('/api/conversations')).json()
    convId=conversations.find((c:{title:string})=>c.title.includes('支持哪些文件格式')).id
    await page.reload()
    await page.getByRole('button',{name:'知识问答',exact:true}).click()
    await page.getByRole('button',{name:/支持哪些文件格式/}).first().click()
    await expect(page.locator('.message.assistant')).toHaveCount(2)
    await page.getByRole('textbox',{name:'问题',exact:true}).fill('停止回答测试')
    await page.getByRole('button',{name:'发送问题'}).click()
    await page.getByRole('button',{name:'停止回答'}).click()
    await expect(page.getByText('未完成',{exact:true})).toBeVisible()
    await page.screenshot({path:'../data/browser-contract.png',fullPage:true})
    await page.getByRole('button',{name:'重试回答'}).click()
    await expect(page.getByRole('button',{name:'发送问题'})).toBeVisible()
    await expect(page.locator('.message.user')).toHaveCount(3)
  }finally{
    if(convId)await request.delete('/api/conversations/'+convId)
    if(kbId)await request.delete('/api/knowledge-bases/'+kbId)
  }
})

test('failed indexing task can be retried through UI',async({page,request})=>{
  const name='browser-retry-'+Date.now()
  let id=''
  try{
    await request.post('http://127.0.0.1:9009/control',{data:{embedding_fails:true}})
    const kb=await (await request.post('/api/knowledge-bases',{data:{name}})).json()
    id=kb.id
    await request.post(`/api/knowledge-bases/${id}/sources`,{data:{name:'失败重试',kind:'upload'}})
    await page.goto('/')
    await page.getByRole('heading',{name,exact:true}).click()
    await page.getByRole('button',{name:/数据源 1/}).click()
    const chooser=page.waitForEvent('filechooser')
    await page.getByRole('button',{name:'选择文件',exact:true}).click()
    await (await chooser).setFiles({name:'failure-'+Date.now()+'.txt',mimeType:'text/plain',buffer:Buffer.from('故障恢复 '+Date.now())})
    await page.getByRole('button',{name:/处理任务/}).click()
    await expect(page.getByText('失败',{exact:true})).toBeVisible({timeout:30000})
    await expect(page.getByText(/embedding 服务返回 HTTP 503/)).toBeVisible()
    await request.post('http://127.0.0.1:9009/control',{data:{embedding_fails:false}})
    await page.getByRole('button',{name:'重试任务'}).click()
    await expect(page.getByText('失败',{exact:true})).not.toBeVisible({timeout:30000})
    await expect(page.getByText('已完成',{exact:true}).first()).toBeVisible()
  }finally{
    await request.post('http://127.0.0.1:9009/control',{data:{embedding_fails:false}})
    if(id)await request.delete('/api/knowledge-bases/'+id)
  }
})

test('folder upload, rejection, source edit and KB delete through UI',async({page,request})=>{
  const folder=mkdtempSync(path.join(tmpdir(),'rag-folder-'))
  mkdirSync(path.join(folder,'nested'))
  writeFileSync(path.join(folder,'nested','nested.txt'),'嵌套目录资料。')
  writeFileSync(path.join(folder,'unsupported.exe'),'rejected')
  const name='browser-folder-'+Date.now()
  let id=''
  try{
    await page.goto('/')
    await page.getByRole('button',{name:'新建知识库'}).click()
    await page.getByLabel('名称',{exact:true}).fill(name)
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await page.getByRole('heading',{name,exact:true}).click()
    id=(await (await request.get('/api/knowledge-bases')).json()).find((k:{name:string})=>k.name===name).id
    await page.getByRole('button',{name:'编辑知识库'}).click()
    await page.getByLabel('描述').fill('已编辑说明')
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await expect(page.getByText('已编辑说明')).toBeVisible()
    await page.getByRole('button',{name:/数据源 0/}).click()
    await page.getByRole('button',{name:'添加数据源'}).click()
    await page.getByLabel('名称',{exact:true}).fill('非法目录')
    await page.getByLabel('接入方式').selectOption('directory')
    await page.getByLabel('容器内目录路径').fill('../outside')
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await expect(page.locator('.modal [role=alert]')).toBeVisible()
    await page.getByRole('button',{name:'取消',exact:true}).click()
    await page.getByRole('button',{name:'添加数据源'}).click()
    await page.getByLabel('名称',{exact:true}).fill('文件夹接入')
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await page.getByRole('button',{name:'编辑数据源'}).click()
    await page.getByLabel('名称',{exact:true}).fill('文件夹接入已编辑')
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await expect(page.getByRole('heading',{name:'文件夹接入已编辑'})).toBeVisible()
    const chooser=page.waitForEvent('filechooser')
    await page.getByRole('button',{name:'选择文件夹',exact:true}).click()
    await (await chooser).setFiles(folder)
    await expect(page.locator('.upload-results')).toContainText('nested/nested.txt')
    await expect(page.locator('.upload-results')).toContainText('拒绝')
    await page.getByRole('button',{name:/文档 1/}).click()
    await expect(page.getByText('已索引',{exact:true})).toBeVisible({timeout:30000})
    await page.getByRole('button',{name:'删除知识库'}).click()
    await page.getByRole('button',{name:'确认删除',exact:true}).click()
    await expect(page.getByRole('heading',{name,exact:true})).not.toBeVisible()
  }finally{
    if(id)await request.delete('/api/knowledge-bases/'+id)
    rmSync(folder,{recursive:true,force:true})
  }
})
